### ISSUE TITLE
a number of conditionals seem to be completely broken with strings now

### ISSUE THREAD

**Issue by AndrewSav** [Adriandmen/05AB1E#54]
I think there is missing "in" in this line:
```
current_command == "\"\u2018\u2019\u201C\u201D"
```
repeated 5 times throughout the code

**Comment by Adriandmen** [comment]
Yes, it's fixed now: https://github.com/Adriandmen/05AB1E/commit/c91e49a1e936ed08ad521d3ca03214a94cc28cc1

**Comment by AndrewSav** [comment]
I'm still not getting any joy:

```
C:\Users\asavinykh\Documents\GitHub\05AB1E>python 05AB1E.py test.abe --debug 
Full program: 5LvNDDi“€ƒ“\}"ÿ ÿ"})

current >> 5  ||  stack: []
current >> L  ||  stack: ['5']
current >> v  ||  stack: [[1, 2, 3, 4, 5]]
NDDi“€ƒ“\}"ÿ ÿ"})

N = 0
Full program: NDDi“€ƒ“\}"ÿ ÿ"})
```

the loop still extends beyond the second `{`.

Any idea why?

**Comment by AndrewSav** [comment]
Ah right, this is because we are not advancing the `current_command` pointer so it exits the string mode instantly after entering it.
